# Generated by Django 3.2.4 on 2021-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
