# Generated by Django 3.2.4 on 2021-07-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_item_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
