# Generated by Django 3.2.4 on 2021-07-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='avisos',
            field=models.BooleanField(verbose_name='deseo recibir avisos'),
        ),
    ]
